apiVersion: apps/v1
kind: Deployment
metadata:
  name: FEGO_Sample_1-deployment
  labels:
    app: FEGO_Sample_1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: FEGO_Sample_1
  template:
    metadata:
      labels:
        app: FEGO_Sample_1
    spec:
      containers:
        - name: FEGO_Sample_1
          image: soumyaregistry.azurecr.io/test_1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 128m
              memory: 256M
            limits:
              cpu: "1"
              memory: 1G
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 6
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 6
            timeoutSeconds: 10
            failureThreshold: 5
          envFrom:
            - configMapRef:
                name: FEGO_Sample_1-config